### ISSUE TITLE
Helper - determineClass - RATED 2

### ISSUE THREAD

**Issue by KrystianKowalak** [KrystianKowalak/support_ticket_site#21]
### Determine Class
- [ ] The `determineClass` function should take in a `value` argument and return the string representing the appropriate class determined by a switch case. This will be a general use function, such as adding the "hidden" or "shown" class to the hide/show eye icons in messages, or "left-align" or "right-align" on the message bubbles.

FROM RACHEL: put a pin on this, don't work on it until she updates the instructions

**Comment by danhalsim** [comment]
done and approved
